title: <p align="center"> Kushagra Sengar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/kushagra-sengar-4aa98b157">LinkedIn</a> |
  <a href="https://github.com/Kushagra007-dev">GitHub</a>
  <br>   
  I am working as a data analyst at Deloitte and I am currently a part of the CoRe Digital, Data, Analytics & Innovation Data Management 
  Platforms team responsible for transforming the way data is managed, 
  delivered and governed within Deloitte.
  <br>
  </p>
theme: jekyll-theme-minimal
